// Runs after `npm install`. Creates .env.local with a random session secret if there is none.
import { existsSync, writeFileSync } from "node:fs";
import { randomBytes } from "node:crypto";
if (!existsSync(".env.local")) {
  writeFileSync(".env.local", `# Generated by scripts/setup.mjs. Never commit this file.\nSESSION_SECRET=${randomBytes(32).toString("hex")}\n\n# Optional: real SMS and WhatsApp through Twilio. See .env.example\n`);
  console.log("Created .env.local with a new SESSION_SECRET");
}
